export const letterSystemFields = [
  { category: "Firm", label: "Firm name", value: "firm.name" },
  { category: "Firm", label: "Firm name uppercase", value: "firm.nameUpper" },
  { category: "Firm", label: "Firm address", value: "firm.address" },
  { category: "Firm", label: "Firm PAN", value: "tenant.pan" },
  { category: "Firm", label: "Firm email", value: "tenant.contactEmail" },
  { category: "Firm", label: "Firm phone", value: "tenant.contactPhone" },
  { category: "Firm", label: "Authorised signatory", value: "firm.signatory.name" },
  { category: "Firm", label: "Signatory relation", value: "firm.signatory.relation" },
  { category: "Firm", label: "Signatory authorization date", value: "firm.signatory.authorizationDate" },
  { category: "Firm", label: "Payment firm name", value: "firm.paymentName" },
  { category: "Project", label: "Project name", value: "project.name" },
  { category: "Project", label: "Project name uppercase", value: "project.nameUpper" },
  { category: "Project", label: "Project city", value: "project.city" },
  { category: "Project", label: "Project city and state", value: "project.cityState" },
  { category: "Project", label: "Project state", value: "project.state" },
  { category: "Project", label: "Project address", value: "project.fullAddress" },
  { category: "Project", label: "Project approval authority", value: "project.approvalAuthority" },
  { category: "Project", label: "Project revenue estate", value: "project.revenueEstate" },
  { category: "Project", label: "RERA number", value: "rera.number" },
  { category: "Payment", label: "Total price", value: "plot.priceInrFormatted" },
  { category: "Payment", label: "Total sale price", value: "payment.totalSalePrice" },
  { category: "Payment", label: "Total payment price", value: "payment.totalPrice" },
  { category: "Payment", label: "Price in words", value: "plot.priceInrWords" },
  { category: "Payment", label: "Per unit price", value: "payment.perUnitPrice" },
  { category: "Payment", label: "BSP rate", value: "plot.bspRate" },
  { category: "Payment", label: "Payment modes", value: "payment.modes" },
  { category: "Payment", label: "Payment entries", value: "payment.entries" },
  { category: "Payment", label: "Payment table rows", value: "payment.tableRows" },
  { category: "Files", label: "Allottee documents", value: "files.allotteeDocuments" },
  { category: "Files", label: "Payment files", value: "files.paymentDocuments" },
  { category: "Files", label: "Additional field files", value: "files.additionalFields" },
  { category: "Files", label: "All supporting documents", value: "files.allSupportingDocuments" },
  { category: "Plot", label: "Plot code", value: "plot.code" },
  { category: "Plot", label: "Plot area (sq yds)", value: "plot.areaSqyd" },
  { category: "Plot", label: "Plot area approx", value: "plot.areaSqydApprox" },
  { category: "Plot", label: "Dimensions", value: "plot.dimensions" },
  { category: "Plot", label: "Prime location", value: "plot.primeLocation" },
  { category: "Plot", label: "North boundary", value: "plot.northBoundary" },
  { category: "Plot", label: "South boundary", value: "plot.southBoundary" },
  { category: "Plot", label: "East boundary", value: "plot.eastBoundary" },
  { category: "Plot", label: "West boundary", value: "plot.westBoundary" },
  { category: "Plot", label: "East size", value: "plot.eastSize" },
  { category: "Plot", label: "East adjoining", value: "plot.eastAdjoining" },
  { category: "Plot", label: "West size", value: "plot.westSize" },
  { category: "Plot", label: "West adjoining", value: "plot.westAdjoining" },
  { category: "Plot", label: "North size", value: "plot.northSize" },
  { category: "Plot", label: "North adjoining", value: "plot.northAdjoining" },
  { category: "Plot", label: "South size", value: "plot.southSize" },
  { category: "Plot", label: "South adjoining", value: "plot.southAdjoining" },
  { category: "Plot", label: "Old plot code", value: "plot.oldCode" },
  { category: "Plot", label: "New plot code", value: "plot.newCode" },
  { category: "Buyer", label: "Buyer name", value: "owner.name" },
  { category: "Buyer", label: "Buyer name uppercase", value: "owner.nameUpper" },
  { category: "Buyer", label: "Buyer name (with relation)", value: "owner.nameWithRelation" },
  { category: "Buyer", label: "Buyer name with relation uppercase", value: "owner.nameWithRelationUpper" },
  { category: "Buyer", label: "Father's name", value: "owner.fatherName" },
  { category: "Buyer", label: "Buyer phone", value: "owner.phone" },
  { category: "Buyer", label: "Buyer mobile number", value: "owner.mobileNo" },
  { category: "Buyer", label: "Buyer address", value: "owner.address" },
  { category: "Buyer", label: "Buyer address multiline", value: "owner.addressMultilineHtml" },
  { category: "Buyer", label: "Buyer address uppercase", value: "owner.addressUpper" },
  { category: "Buyer", label: "Aadhaar number", value: "owner.aadhaarNo" },
  { category: "Buyer", label: "PAN number", value: "owner.panNo" },
  { category: "Buyer", label: "Share (joint allotment)", value: "owner.share" },
  { category: "Joint allottee", label: "Name", value: "owner2.name" },
  { category: "Joint allottee", label: "Name with relation", value: "owner2.nameWithRelation" },
  { category: "Joint allottee", label: "Name with relation uppercase", value: "owner2.nameWithRelationUpper" },
  { category: "Joint allottee", label: "Address", value: "owner2.address" },
  { category: "Joint allottee", label: "Address uppercase", value: "owner2.addressUpper" },
  { category: "Joint allottee", label: "Address multiline", value: "owner2.addressMultilineHtml" },
  { category: "Joint allottee", label: "Aadhaar number", value: "owner2.aadhaarNo" },
  { category: "Joint allottee", label: "PAN number", value: "owner2.panNo" },
  { category: "Joint allottee", label: "Mobile number", value: "owner2.mobileNo" },
  { category: "Joint allottee", label: "Share", value: "owner2.share" },
  { category: "Transfer", label: "Seller name", value: "seller.name" },
  { category: "Transfer", label: "Seller name with relation", value: "seller.nameWithRelation" },
  { category: "Transfer", label: "Seller relation", value: "seller.relationPrefix" },
  { category: "Transfer", label: "Seller father's / spouse's name", value: "seller.fatherName" },
  { category: "Transfer", label: "Seller address", value: "seller.address" },
  { category: "Transfer", label: "Seller phone", value: "seller.phone" },
  { category: "Transfer", label: "Seller email", value: "seller.email" },
  { category: "Transfer", label: "Seller Aadhaar number", value: "seller.aadhaarNo" },
  { category: "Transfer", label: "Seller PAN number", value: "seller.panNo" },
  { category: "Transfer", label: "Original allotment letter no.", value: "original.allotmentNumber" },
  { category: "Transfer", label: "Original allotment letter date", value: "original.allotmentDate" },
  { category: "Buyer", label: "Allotment date", value: "ownership.effectiveDate" },
  { category: "Buyer", label: "Allotment date dots", value: "ownership.effectiveDateDots" },
  { category: "Buyer", label: "Allotment day ordinal", value: "ownership.effectiveDayOrdinal" },
  { category: "Buyer", label: "Allotment month", value: "ownership.effectiveMonth" },
  { category: "Buyer", label: "Allotment year", value: "ownership.effectiveYear" },
  { category: "Buyer", label: "E-stamp number", value: "extra.eStampNumber" },
  { category: "Buyer", label: "Witness details", value: "extra.witnessDetails" },
  { category: "Buyer", label: "Witness 1 name", value: "witness.1.name" },
  { category: "Buyer", label: "Witness 1 address", value: "witness.1.address" },
  { category: "Buyer", label: "Witness 1 contact", value: "witness.1.phone" },
  { category: "Buyer", label: "Witness 2 name", value: "witness.2.name" },
  { category: "Buyer", label: "Witness 2 address", value: "witness.2.address" },
  { category: "Buyer", label: "Witness 2 contact", value: "witness.2.phone" },
  { category: "Document", label: "Document number", value: "document.number" },
  { category: "Document", label: "Document date", value: "document.date" },
  { category: "Document", label: "Document date (DD.MM.YYYY)", value: "document.dateDots" },
  { category: "Document", label: "Document date (DD/MM/YYYY)", value: "document.dateSlashes" },
  { category: "Document", label: "Today's date", value: "today" },
  { category: "Document", label: "Document place", value: "document.place" },
  { category: "Document", label: "Stamp amount", value: "stamp.amount" },
  { category: "Document", label: "Stamp 1 number", value: "stamp.estampNo" },
  { category: "Document", label: "Stamp 1 date", value: "stamp.date" },
  { category: "Document", label: "Stamp 2 number", value: "stamp.2.estampNo" },
  { category: "Document", label: "Stamp 2 date", value: "stamp.2.date" },
  { category: "Document", label: "Stamp 3 number", value: "stamp.3.estampNo" },
  { category: "Document", label: "Stamp 3 date", value: "stamp.3.date" },
  { category: "Document", label: "Agreement place", value: "agreement.place" },
  { category: "Document", label: "Witness place", value: "witness.place" },
] as const;

export type LetterSystemField = (typeof letterSystemFields)[number];
