export const letterSystemFields = [
  { category: "Firm", label: "Firm name", value: "firm.name" },
  { category: "Firm", label: "Firm address", value: "firm.address" },
  { category: "Firm", label: "Firm PAN", value: "tenant.pan" },
  { category: "Firm", label: "Firm email", value: "tenant.contactEmail" },
  { category: "Firm", label: "Firm phone", value: "tenant.contactPhone" },
  { category: "Firm", label: "Authorised signatory", value: "firm.signatory.name" },
  { category: "Project", label: "Project name", value: "project.name" },
  { category: "Project", label: "Project city", value: "project.city" },
  { category: "Project", label: "Project address", value: "project.fullAddress" },
  { category: "Project", label: "RERA number", value: "rera.number" },
  { category: "Payment", label: "Total price", value: "plot.priceInrFormatted" },
  { category: "Payment", label: "Price in words", value: "plot.priceInrWords" },
  { category: "Payment", label: "Per unit price", value: "payment.perUnitPrice" },
  { category: "Payment", label: "Payment modes", value: "payment.modes" },
  { category: "Payment", label: "Payment entries", value: "payment.entries" },
  { category: "Files", label: "Allottee documents", value: "files.allotteeDocuments" },
  { category: "Files", label: "Payment files", value: "files.paymentDocuments" },
  { category: "Files", label: "Additional field files", value: "files.additionalFields" },
  { category: "Files", label: "All supporting documents", value: "files.allSupportingDocuments" },
  { category: "Plot", label: "Plot code", value: "plot.code" },
  { category: "Plot", label: "Plot area (sq yds)", value: "plot.areaSqyd" },
  { category: "Plot", label: "Plot area approx", value: "plot.areaSqydApprox" },
  { category: "Plot", label: "Dimensions", value: "plot.dimensions" },
  { category: "Plot", label: "Prime location", value: "plot.primeLocation" },
  { category: "Plot", label: "North boundary", value: "plot.northBoundary" },
  { category: "Plot", label: "South boundary", value: "plot.southBoundary" },
  { category: "Plot", label: "East boundary", value: "plot.eastBoundary" },
  { category: "Plot", label: "West boundary", value: "plot.westBoundary" },
  { category: "Buyer", label: "Buyer name", value: "owner.name" },
  { category: "Buyer", label: "Buyer name (with relation)", value: "owner.nameWithRelation" },
  { category: "Buyer", label: "Father's name", value: "owner.fatherName" },
  { category: "Buyer", label: "Buyer phone", value: "owner.phone" },
  { category: "Buyer", label: "Buyer address", value: "owner.address" },
  { category: "Buyer", label: "Aadhaar number", value: "owner.aadhaarNo" },
  { category: "Buyer", label: "PAN number", value: "owner.panNo" },
  { category: "Buyer", label: "Allotment date", value: "ownership.effectiveDate" },
  { category: "Buyer", label: "E-stamp number", value: "extra.eStampNumber" },
  { category: "Buyer", label: "Witness details", value: "extra.witnessDetails" },
  { category: "Document", label: "Document number", value: "document.number" },
  { category: "Document", label: "Document date", value: "document.date" },
  { category: "Document", label: "Today's date", value: "today" },
] as const;

export type LetterSystemField = (typeof letterSystemFields)[number];
