export const letterSystemFields = [
  { category: "Firm", label: "Firm name", value: "firm.name" },
  { category: "Firm", label: "Firm address", value: "firm.address" },
  { category: "Firm", label: "Firm PAN", value: "tenant.pan" },
  { category: "Firm", label: "Firm email", value: "tenant.contactEmail" },
  { category: "Firm", label: "Firm phone", value: "tenant.contactPhone" },
  { category: "Firm", label: "Authorised signatory", value: "firm.signatory.name" },
  { category: "Project", label: "Project name", value: "project.name" },
  { category: "Project", label: "Project city", value: "project.city" },
  { category: "Project", label: "Project address", value: "project.address" },
  { category: "Project", label: "RERA number", value: "rera.number" },
  { category: "Payment", label: "Total price", value: "plot.priceInrFormatted" },
  { category: "Payment", label: "Price in words", value: "plot.priceInrWords" },
  { category: "Payment", label: "Per unit price", value: "payment.perUnitPrice" },
  { category: "Payment", label: "Payment modes", value: "payment.modes" },
  { category: "Payment", label: "Payment entries", value: "payment.entries" },
  { category: "Plot", label: "Plot code", value: "plot.code" },
  { category: "Plot", label: "Plot area", value: "plot.areaSqyd" },
  { category: "Plot", label: "Dimensions", value: "plot.dimensions" },
  { category: "Plot", label: "Prime location", value: "plot.primeLocation" },
  { category: "Plot", label: "North boundary", value: "plot.northBoundary" },
  { category: "Plot", label: "South boundary", value: "plot.southBoundary" },
  { category: "Plot", label: "East boundary", value: "plot.eastBoundary" },
  { category: "Plot", label: "West boundary", value: "plot.westBoundary" },
  { category: "Extra", label: "Allottee name", value: "owner.name" },
  { category: "Extra", label: "Allottee phone", value: "owner.phone" },
  { category: "Extra", label: "Allotment date", value: "ownership.effectiveDate" },
  { category: "Extra", label: "E-stamp number", value: "extra.eStampNumber" },
  { category: "Extra", label: "Witness details", value: "extra.witnessDetails" },
] as const;

export type LetterSystemField = (typeof letterSystemFields)[number];
