import Link from "next/link";
import { Download } from "lucide-react";
import { getCrmReports } from "@/server/services/crm";
import { CrmNav } from "../crm-nav";
import { requireCrmContext } from "../crm-page-context";

export const dynamic = "force-dynamic";
export default async function ReportsPage() {
  const { context } = await requireCrmContext("crm.reports"); const report = await getCrmReports(context);
  return <main className="px-4 py-6 lg:px-8"><CrmNav canManageSettings/><div className="mb-5 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-semibold">CRM reports</h1><p className="mt-2 text-sm text-slate-600">Funnel performance, team discipline, feedback, lead-source conversion, and booked value.</p></div><Link className="btn-outline h-10 px-4" href="/api/v1/crm/export"><Download size={16}/>Export leads</Link></div>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Leads" value={report.totals.leads}/><Metric label="Bookings" value={report.totals.bookings}/><Metric label="Booked value" value={`₹${report.totals.revenue.toLocaleString("en-IN")}`}/><Metric label="Average feedback" value={`${report.totals.averageFeedback.toFixed(1)} / 5`}/></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-2"><div className="rounded-lg border border-slate-200 bg-white p-4"><h2 className="font-semibold">Funnel</h2><div className="mt-4 space-y-3">{report.funnel.map(([name,count], index) => { const width = report.funnel[0][1] ? Math.max(4, Math.round(count / report.funnel[0][1] * 100)) : 0; return <div key={name}><div className="mb-1 flex justify-between text-sm"><span>{index + 1}. {name}</span><b>{count}</b></div><div className="h-2 rounded bg-slate-100"><div className="h-2 rounded bg-[#2D5986]" style={{ width: `${width}%` }}/></div></div>; })}</div></div><div className="rounded-lg border border-slate-200 bg-white p-4"><h2 className="font-semibold">Lead-source ROI</h2><table className="mt-4 w-full text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr><th className="py-2">Source</th><th>Leads</th><th>Bookings</th><th>Value</th></tr></thead><tbody className="divide-y divide-slate-100">{report.sources.map((row) => <tr key={row.source}><td className="py-3 font-medium">{row.source}</td><td>{row.leads}</td><td>{row.bookings}</td><td>₹{row.revenue.toLocaleString("en-IN")}</td></tr>)}</tbody></table></div></section>
    <section className="mt-6 overflow-x-auto rounded-lg border border-slate-200 bg-white p-4"><h2 className="font-semibold">Employee performance</h2><table className="mt-4 w-full min-w-[720px] text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr><th className="py-2">Employee</th><th>Assigned leads</th><th>Calls</th><th>Visits</th><th>Bookings</th><th>Conversion</th></tr></thead><tbody className="divide-y divide-slate-100">{report.employee.map((row) => <tr key={row.name}><td className="py-3 font-medium">{row.name}</td><td>{row.leads}</td><td>{row.calls}</td><td>{row.visits}</td><td>{row.bookings}</td><td>{row.conversion}%</td></tr>)}</tbody></table></section>
  </main>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-lg border border-slate-200 bg-white p-4"><div className="text-2xl font-semibold">{value}</div><div className="mt-1 text-xs font-medium uppercase text-slate-500">{label}</div></div>; }
