import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function buildGeneratedDocumentPdf(input: {
  title: string;
  number?: string | null;
  tenantName: string;
  body: string[];
}) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595.28, 841.89]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  page.drawText(input.tenantName, { x: 48, y: 780, size: 18, font: bold, color: rgb(0.04, 0.1, 0.22) });
  page.drawText(input.title, { x: 48, y: 744, size: 14, font: bold, color: rgb(0.1, 0.1, 0.1) });
  if (input.number) page.drawText(`Document No: ${input.number}`, { x: 48, y: 720, size: 10, font, color: rgb(0.3, 0.3, 0.3) });

  let y = 675;
  for (const line of input.body) {
    const chunks = line.match(/.{1,92}(\s|$)/g) ?? [line];
    for (const chunk of chunks) {
      page.drawText(chunk.trim(), { x: 48, y, size: 11, font, color: rgb(0.15, 0.15, 0.15) });
      y -= 18;
    }
    y -= 8;
  }

  page.drawText("Generated by Kalman Estate OS", { x: 48, y: 60, size: 9, font, color: rgb(0.45, 0.45, 0.45) });
  return Buffer.from(await pdf.save());
}
