import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { buildLetterStudioPdfFromHtml, isLetterStudioHtml } from "./ambey-allotment-pdf";
import { renderLetterHtmlToPdf } from "./letter-pdf-puppeteer";

export async function buildGeneratedDocumentPdf(input: {
  title: string;
  number?: string | null;
  tenantName: string;
  body: string[];
}) {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const pages = [];
  let page = pdf.addPage([595.28, 841.89]);
  pages.push(page);

  page.drawText(input.tenantName, { x: 48, y: 780, size: 18, font: bold, color: rgb(0.04, 0.1, 0.22) });
  page.drawText(input.title, { x: 48, y: 744, size: 14, font: bold, color: rgb(0.1, 0.1, 0.1) });
  if (input.number) page.drawText(`Document No: ${input.number}`, { x: 48, y: 720, size: 10, font, color: rgb(0.3, 0.3, 0.3) });

  let y = 675;
  for (const line of input.body) {
    const chunks = line.match(/.{1,92}(\s|$)/g) ?? [line];
    for (const chunk of chunks) {
      if (y < 82) {
        page = pdf.addPage([595.28, 841.89]);
        pages.push(page);
        y = 780;
      }
      page.drawText(chunk.trim(), { x: 48, y, size: 11, font, color: rgb(0.15, 0.15, 0.15) });
      y -= 18;
    }
    y -= 8;
  }

  pages.forEach((currentPage, index) => {
    currentPage.drawText("Generated by WIDESTATE OS", { x: 48, y: 42, size: 9, font, color: rgb(0.45, 0.45, 0.45) });
    currentPage.drawText(`Page ${index + 1} of ${pages.length}`, { x: 480, y: 42, size: 9, font, color: rgb(0.45, 0.45, 0.45) });
  });
  return Buffer.from(await pdf.save());
}

export async function buildGeneratedDocumentPdfFromHtml(input: {
  title: string;
  number?: string | null;
  tenantName: string;
  html: string;
}) {
  if (isLetterStudioHtml(input.html)) {
    // Prefer exact Chromium rendering, but do not block production document generation when the
    // server is missing Chromium/Puppeteer. Fall back to the lightweight renderer so every tenant
    // can still generate a usable PDF.
    try {
      return await renderLetterHtmlToPdf(input.html);
    } catch (error) {
      console.error("[letter-pdf] Chromium render failed:", error);
      console.warn("[letter-pdf] Falling back to approximate pdf-lib renderer.");
      return buildLetterStudioPdfFromHtml(input.html);
    }
  }

  return buildGeneratedDocumentPdf({
    title: input.title,
    number: input.number,
    tenantName: input.tenantName,
    body: htmlToLines(input.html),
  });
}

function htmlToLines(html: string) {
  const text = html
    .replace(/<\/(p|div|h[1-6]|li|tr)>/gi, "\n")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<li>/gi, "- ")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");

  return text
    .split(/\n+/)
    .map((line) => line.trim())
    .filter(Boolean);
}
