"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, CalendarPlus, CheckCircle2, ClipboardList, ExternalLink, Mail, MapPin, MessageCircle, Phone, Save, Send, TicketCheck, UserRoundCheck } from "lucide-react";
import { crmRequest, inputDateTime } from "../../crm-api";
import { formatCrmLabel } from "../../crm-nav";

type User = { id: string; name: string; email: string; phone: string | null; role: string };
type Project = { id: string; name: string; city: string | null; state: string | null };
type Plot = { id: string; projectId: string; code: string };
type Activity = { id: string; type: string; title: string; notes: string | null; outcome: string | null; occurredAt: string; actorUserId: string | null };
type FollowUp = { id: string; actionType: string; reason: string | null; dueAt: string; status: string; outcome: string | null };
type Visit = { id: string; visitCode: string; projectId: string; scheduledAt: string; status: string; assignedSalespersonId: string | null; customerResponse: string | null };
type Booking = { id: string; bookingCode: string; projectId: string; plotId: string | null; amountInr: string | number | null; createdAt: string };
type Data = {
  contact: { id: string; clientType: string | null };
  lead: { id: string; leadCode: string; name: string; primaryPhone: string; alternatePhone: string | null; whatsappPhone: string | null; email: string | null; city: string | null; area: string | null; status: string; potential: string; score: number; interestedProjectId: string | null; interestedProperty: string | null; propertyType: string | null; budgetMinInr: string | number | null; budgetMaxInr: string | number | null; purchaseTimeline: string | null; purpose: string | null; priceDiscussedInr: string | number | null; offersDiscounts: string | null; paymentPreference: string | null; negotiationStatus: string | null; mainObjections: string | null; competitorComparison: string | null; requestedInformation: string | null; notes: string | null; tags: string[]; assignedCallerId: string | null; assignedSalespersonId: string | null; nextFollowUpAt: string | null };
  activities: Activity[]; followUps: FollowUp[]; visits: Visit[]; bookings: Booking[];
  feedback: Array<{ id: string; rating: number; comments: string | null; createdAt: string }>;
  tickets: Array<{ id: string; ticketCode: string; category: string; subject: string; status: string; createdAt: string }>;
  templates: Array<{ id: string; name: string; channel: string; subject: string | null; body: string }>;
  users: User[]; projects: Project[]; plots: Plot[];
};

const OUTCOMES = ["Interested", "Not interested", "Asked to call later", "Visit agreed", "Visit scheduled", "Price discussion", "Negotiation", "Booking discussion", "Wrong number", "No response", "Other"];
const NEXT_ACTIONS = ["Call", "WhatsApp", "Send details", "Schedule visit", "Price discussion", "Manager callback", "No further action"];

export function LeadWorkspace({ data, canAssign }: { data: Data; canAssign: boolean }) {
  const router = useRouter(); const { lead } = data;
  const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const userMap = Object.fromEntries(data.users.map((user) => [user.id, user]));
  const projectMap = Object.fromEntries(data.projects.map((project) => [project.id, project]));
  const whatsapp = digits(lead.whatsappPhone || lead.primaryPhone);
  async function action(body: Record<string, unknown>, success: string) {
    setSaving(true); setError(""); setMessage("");
    try { const result = await crmRequest<Record<string, unknown>>(`/api/v1/crm/leads/${lead.id}/actions`, "POST", body); setMessage(success); router.refresh(); return result; }
    catch (cause) { setError(cause instanceof Error ? cause.message : "The action could not be saved."); return null; }
    finally { setSaving(false); }
  }
  async function editLead(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); setError(""); setMessage("");
    try {
      await crmRequest(`/api/v1/crm/leads/${lead.id}`, "PATCH", {
        name: value(form,"name"), primaryPhone: value(form,"primaryPhone"), whatsappPhone: value(form,"whatsappPhone") || null,
        alternatePhone: value(form,"alternatePhone") || null, email: value(form,"email"), city: value(form,"city") || null,
        area: value(form,"area") || null, propertyType: value(form,"propertyType") || null,
        interestedProperty: value(form,"interestedProperty") || null, purchaseTimeline: value(form,"purchaseTimeline") || null,
        purpose: value(form,"purpose") || null, notes: value(form,"notes") || null,
        priceDiscussedInr: value(form,"priceDiscussedInr") ? Number(value(form,"priceDiscussedInr")) : null,
        offersDiscounts: value(form,"offersDiscounts") || null, paymentPreference: value(form,"paymentPreference") || null,
        negotiationStatus: value(form,"negotiationStatus") || null, mainObjections: value(form,"mainObjections") || null,
        competitorComparison: value(form,"competitorComparison") || null, requestedInformation: value(form,"requestedInformation") || null,
      });
      setMessage("Lead details updated."); router.refresh();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not update the lead."); }
    finally { setSaving(false); }
  }
  async function callClosure(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const nextAction = value(form, "nextAction"); const nextAt = value(form, "nextFollowUpAt");
    const result = await action({ action: "activity", type: value(form, "type"), notes: value(form, "notes"), outcome: value(form, "outcome"), durationMinutes: Number(value(form, "durationMinutes") || 0), potential: value(form, "potential"), nextAction, nextFollowUpAt: nextAction === "No further action" ? null : new Date(nextAt).toISOString() }, "Call and next action saved.");
    if (result) event.currentTarget.reset();
  }
  async function simple(event: FormEvent<HTMLFormElement>, actionName: string, success: string) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const body: Record<string, unknown> = { action: actionName };
    form.forEach((item, key) => { if (item !== "") body[key] = item; });
    if (body.scheduledAt) body.scheduledAt = new Date(String(body.scheduledAt)).toISOString();
    if (body.dueAt) body.dueAt = new Date(String(body.dueAt)).toISOString();
    if (body.visitorCount) body.visitorCount = Number(body.visitorCount);
    if (body.amountInr) body.amountInr = Number(body.amountInr);
    if (body.rating) body.rating = Number(body.rating);
    if (body.purchaseProbability) body.purchaseProbability = Number(body.purchaseProbability);
    if (typeof body.propertiesShown === "string") body.propertiesShown = String(body.propertiesShown).split(",").map((item) => item.trim()).filter(Boolean);
    if (typeof body.propertiesLiked === "string") body.propertiesLiked = String(body.propertiesLiked).split(",").map((item) => item.trim()).filter(Boolean);
    if (typeof body.customerDisliked === "string") body.customerDisliked = String(body.customerDisliked).split(",").map((item) => item.trim()).filter(Boolean);
    if (body.nextAction === "No further action") delete body.nextFollowUpAt;
    if (body.nextFollowUpAt) body.nextFollowUpAt = new Date(String(body.nextFollowUpAt)).toISOString();
    body.pickupRequired = form.get("pickupRequired") === "on";
    const result = await action(body, success); if (result) event.currentTarget.reset();
  }
  return <div className="mx-auto max-w-[1500px]">
    <Link className="mb-4 inline-flex items-center gap-2 text-sm text-slate-600 hover:text-slate-950" href="/app/crm/leads"><ArrowLeft size={15}/>All leads</Link>
    <header className="flex flex-col gap-4 border-b border-slate-200 pb-5 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-3xl font-semibold">{lead.name}</h1><span className="chip bg-slate-100 text-slate-700">{lead.leadCode}</span><span className="chip bg-[#E8F0F7] text-[#2D5986]">{formatCrmLabel(lead.status)}</span><span className="chip bg-amber-50 text-amber-800">{formatCrmLabel(lead.potential)} · {lead.score}</span></div><p className="mt-2 text-sm text-slate-600">{lead.primaryPhone}{lead.city ? ` · ${lead.city}` : ""}{lead.interestedProjectId ? ` · ${projectMap[lead.interestedProjectId]?.name || "Project"}` : ""}</p></div>
      <div className="flex flex-wrap gap-2">{canAssign ? <Link className="btn-outline h-10 px-4" href={`/app/crm/contacts/${data.contact.id}`}><UserRoundCheck size={16}/>View full profile</Link> : null}<Link className="btn-outline h-10 px-4" href={`/crm/visit-brief/${lead.id}${data.visits[0] ? `?visitId=${data.visits[0].id}` : ""}`} target="_blank"><ClipboardList size={16}/>Print visit sheet</Link>{data.visits[0] && lead.assignedSalespersonId ? <button className="btn-outline h-10 px-4" disabled={saving} onClick={() => void action({ action: "send_brief" }, "Visit brief sent to the assigned salesperson.")} type="button"><Send size={16}/>Send to salesperson</button> : null}<a className="btn-outline h-10 px-4" href={`tel:${lead.primaryPhone}`}><Phone size={16}/>Call</a><a className="btn-outline h-10 px-4" href={`https://wa.me/${whatsapp}?text=${encodeURIComponent(`Hello ${lead.name}, following up on your property enquiry.`)}`} rel="noreferrer" target="_blank"><MessageCircle size={16}/>WhatsApp</a>{lead.email ? <a className="btn-outline h-10 px-4" href={`mailto:${lead.email}`}><Mail size={16}/>Email</a> : null}</div>
    </header>
    {error ? <div className="sticky top-3 z-20 mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div> : null}{message ? <div className="sticky top-3 z-20 mt-4 rounded-lg border border-green-200 bg-green-50 p-3 text-sm text-green-800">{message}</div> : null}
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_390px]">
      <div className="space-y-6">
        <section className="rounded-lg border-2 border-[#2D5986]/30 bg-white p-5"><div className="flex items-center gap-2"><Phone className="text-[#2D5986]" size={18}/><h2 className="font-semibold">Close call and set next action</h2></div><p className="mt-1 text-sm text-slate-500">Every call needs an outcome and a next action so the lead cannot disappear.</p>
          <form className="mt-4 grid gap-4 md:grid-cols-2" onSubmit={callClosure}><Select label="Call type" name="type" options={[["OUTGOING_CALL","Outgoing call"],["INCOMING_CALL","Incoming call"],["NOTE","Note"]]}/><Select label="Result" name="outcome" options={OUTCOMES.map((item) => [item,item])}/><Select label="Potential" name="potential" options={[["COLD","Cold"],["WARM","Warm"],["HOT","Hot"]]}/><Field label="Duration (minutes)" name="durationMinutes" type="number"/><Select label="Next action" name="nextAction" options={NEXT_ACTIONS.map((item) => [item,item])}/><Field label="Next date and time" name="nextFollowUpAt" type="datetime-local" defaultValue={inputDateTime()}/><label className="md:col-span-2"><span className="label">Call notes *</span><textarea className="input min-h-24 w-full" name="notes" required/></label><button className="btn-primary h-10 px-4 md:col-span-2" disabled={saving}><Save size={16}/>Save call and next action</button></form>
        </section>
        <section className="rounded-lg border border-slate-200 bg-white"><div className="border-b border-slate-200 p-4"><h2 className="font-semibold">Relationship timeline</h2><p className="mt-1 text-xs text-slate-500">Chronological activity is permanent and remains with the firm.</p></div><div className="divide-y divide-slate-100">{data.activities.map((item) => <div className="grid gap-2 p-4 sm:grid-cols-[150px_1fr]" key={item.id}><div className="text-xs text-slate-500">{new Date(item.occurredAt).toLocaleString("en-IN")}</div><div><div className="font-medium">{item.title}</div>{item.outcome ? <div className="mt-1 text-sm text-slate-700">Outcome: {item.outcome}</div> : null}{item.notes ? <p className="mt-1 whitespace-pre-wrap text-sm text-slate-600">{item.notes}</p> : null}<div className="mt-1 text-xs text-slate-400">{item.actorUserId ? userMap[item.actorUserId]?.name || "Team member" : "System"}</div></div></div>)}{!data.activities.length ? <div className="p-8 text-center text-sm text-slate-500">No activity yet.</div> : null}</div></section>
      </div>
      <aside className="space-y-4">
        <section className="rounded-lg border border-slate-200 bg-white p-4"><h2 className="font-semibold">Current details</h2><dl className="mt-3 space-y-3 text-sm"><Row label="Caller" value={userMap[lead.assignedCallerId ?? ""]?.name || "Unassigned"}/><Row label="Salesperson" value={userMap[lead.assignedSalespersonId ?? ""]?.name || "Unassigned"}/><Row label="Requirement" value={[lead.propertyType, lead.interestedProperty].filter(Boolean).join(" · ") || "Not specified"}/><Row label="Budget" value={budget(lead.budgetMinInr, lead.budgetMaxInr)}/><Row label="Timeline" value={lead.purchaseTimeline || "Not specified"}/><Row label="Purpose" value={lead.purpose || "Not specified"}/><Row label="Next action" value={lead.nextFollowUpAt ? new Date(lead.nextFollowUpAt).toLocaleString("en-IN") : "Not scheduled"}/></dl>{lead.notes ? <p className="mt-4 whitespace-pre-wrap rounded-md bg-slate-50 p-3 text-sm text-slate-600">{lead.notes}</p> : null}</section>
        <ActionBox icon={<Save size={17}/>} title="Edit client and sales details"><form className="grid gap-3" onSubmit={editLead}><Field label="Name" name="name" defaultValue={lead.name} required/><Field label="Primary phone" name="primaryPhone" defaultValue={lead.primaryPhone} required/><Field label="WhatsApp" name="whatsappPhone" defaultValue={lead.whatsappPhone ?? ""}/><Field label="Alternate phone" name="alternatePhone" defaultValue={lead.alternatePhone ?? ""}/><Field label="Email" name="email" defaultValue={lead.email ?? ""}/><Field label="City" name="city" defaultValue={lead.city ?? ""}/><Field label="Area" name="area" defaultValue={lead.area ?? ""}/><Field label="Property type" name="propertyType" defaultValue={lead.propertyType ?? ""}/><Field label="Specific requirement" name="interestedProperty" defaultValue={lead.interestedProperty ?? ""}/><Field label="Purchase timeline" name="purchaseTimeline" defaultValue={lead.purchaseTimeline ?? ""}/><Field label="Purpose" name="purpose" defaultValue={lead.purpose ?? ""}/><Field label="Price discussed (₹)" name="priceDiscussedInr" type="number" defaultValue={lead.priceDiscussedInr == null ? "" : String(lead.priceDiscussedInr)}/><Field label="Offers / discounts" name="offersDiscounts" defaultValue={lead.offersDiscounts ?? ""}/><Field label="Payment preference" name="paymentPreference" defaultValue={lead.paymentPreference ?? ""}/><Field label="Negotiation status" name="negotiationStatus" defaultValue={lead.negotiationStatus ?? ""}/><Field label="Main objections" name="mainObjections" defaultValue={lead.mainObjections ?? ""}/><Field label="Competitor comparison" name="competitorComparison" defaultValue={lead.competitorComparison ?? ""}/><Field label="What the client asked for" name="requestedInformation" defaultValue={lead.requestedInformation ?? ""}/><Field label="Notes" name="notes" defaultValue={lead.notes ?? ""}/><ActionButton saving={saving}>Save details</ActionButton></form></ActionBox>
        {data.templates.length ? <ActionBox icon={<MessageCircle size={17}/>} title="Communication templates"><div className="space-y-2">{data.templates.map((template) => { const messageText = fillTemplate(template.body, lead.name, lead.interestedProjectId ? projectMap[lead.interestedProjectId]?.name : undefined); return <a className="flex items-center justify-between gap-3 rounded-md border border-slate-200 p-3 text-sm hover:border-[#2D5986]" href={template.channel === "EMAIL" && lead.email ? `mailto:${lead.email}?subject=${encodeURIComponent(template.subject || template.name)}&body=${encodeURIComponent(messageText)}` : `https://wa.me/${whatsapp}?text=${encodeURIComponent(messageText)}`} key={template.id} onClick={() => { void action({ action: "activity", type: "MESSAGE_OPENED", notes: `${template.channel} template opened: ${template.name}`, outcome: "Opened in external app", nextAction: "No further action", nextFollowUpAt: null }, "Communication recorded."); }} rel="noreferrer" target="_blank"><div><div className="font-medium">{template.name}</div><div className="line-clamp-2 text-xs text-slate-500">{messageText}</div></div><ExternalLink className="shrink-0" size={15}/></a>; })}</div></ActionBox> : null}
        {canAssign ? <ActionBox icon={<UserRoundCheck size={17}/>} title="Assign lead"><form className="grid gap-3" onSubmit={(event) => simple(event, "assign", "Assignment updated.")}><UserSelect label="Caller" name="callerId" users={data.users} defaultValue={lead.assignedCallerId}/><UserSelect label="Salesperson" name="salespersonId" users={data.users} defaultValue={lead.assignedSalespersonId}/><Field label="Reason" name="reason" required/><ActionButton saving={saving}>Update assignment</ActionButton></form></ActionBox> : null}
        <ActionBox icon={<CalendarPlus size={17}/>} title="Schedule follow-up"><form className="grid gap-3" onSubmit={(event) => simple(event, "follow_up", "Follow-up scheduled.")}><Field label="Action" name="actionType" required placeholder="Call, WhatsApp, send details..."/><Field label="Due" name="dueAt" type="datetime-local" defaultValue={inputDateTime()} required/><UserSelect label="Assigned to" name="assignedToId" users={data.users}/><Field label="Reason" name="reason"/><ActionButton saving={saving}>Schedule</ActionButton></form></ActionBox>
        {data.followUps.some((item) => ["PENDING", "OVERDUE"].includes(item.status)) ? <ActionBox icon={<CheckCircle2 size={17}/>} title="Complete follow-up"><form className="grid gap-3" onSubmit={(event) => simple(event, "complete_follow_up", "Follow-up completed.")}><label><span className="label">Follow-up</span><select className="select h-10 w-full" name="followUpId" required>{data.followUps.filter((item) => ["PENDING", "OVERDUE"].includes(item.status)).map((item) => <option key={item.id} value={item.id}>{item.actionType} · {new Date(item.dueAt).toLocaleDateString("en-IN")}</option>)}</select></label><Field label="Outcome" name="outcome" required/><Select label="Next action" name="nextAction" options={NEXT_ACTIONS.map((item) => [item,item])}/><Field label="Next date and time" name="nextFollowUpAt" type="datetime-local" defaultValue={inputDateTime()}/><ActionButton saving={saving}>Complete and continue</ActionButton></form></ActionBox> : null}
        <ActionBox icon={<MapPin size={17}/>} title="Schedule site visit"><form className="grid gap-3" onSubmit={(event) => simple(event, "visit", "Visit scheduled.")}><ProjectSelect projects={data.projects}/><Field label="Date and time" name="scheduledAt" type="datetime-local" defaultValue={inputDateTime()} required/><Field label="Visitors" name="visitorCount" type="number" defaultValue="1" required/><UserSelect label="Salesperson" name="assignedSalespersonId" users={data.users}/><Field label="Visit purpose" name="visitPurpose"/><Field label="Property / unit to show" name="propertyToShow"/><label className="inline-flex items-center gap-2 text-sm"><input name="pickupRequired" type="checkbox"/>Pickup required</label><Field label="Special instructions" name="specialRequirements"/><ActionButton saving={saving}>Confirm visit</ActionButton></form></ActionBox>
        {data.visits.length ? <ActionBox icon={<CheckCircle2 size={17}/>} title="Update site visit"><form className="grid gap-3" onSubmit={(event) => simple(event, "update_visit", "Visit updated.")}><label><span className="label">Visit</span><select className="select h-10 w-full" name="visitId" required>{data.visits.map((visit) => <option key={visit.id} value={visit.id}>{visit.visitCode} · {new Date(visit.scheduledAt).toLocaleDateString("en-IN")}</option>)}</select></label><Select label="Result" name="status" options={[["VISITED","Visited"],["DID_NOT_VISIT","Did not visit"],["RESCHEDULED","Rescheduled"],["CANCELLED","Cancelled"]]}/><Field label="Customer response" name="customerResponse"/><Field label="Properties shown (comma separated)" name="propertiesShown"/><Field label="Properties liked (comma separated)" name="propertiesLiked"/><Field label="Customer disliked (comma separated)" name="customerDisliked"/><Field label="Revised requirement" name="revisedRequirement"/><Field label="Confirmed budget (₹)" name="budgetConfirmedInr" type="number"/><Field label="Objections" name="objections"/><Field label="Purchase probability (%)" name="purchaseProbability" type="number"/><Field label="Customer next action" name="customerNextAction"/><Field label="Salesperson next action" name="salespersonNextAction"/><Field label="Next follow-up" name="nextFollowUpAt" type="datetime-local" defaultValue={inputDateTime()}/><ActionButton saving={saving}>Save visit result</ActionButton></form></ActionBox> : null}
        {data.visits.some((visit) => visit.status === "VISITED") ? <ActionBox icon={<CheckCircle2 size={17}/>} title="Record customer feedback"><form className="grid gap-3" onSubmit={(event) => simple(event, "feedback", "Feedback recorded.")}><label><span className="label">Visit</span><select className="select h-10 w-full" name="visitId"><option value="">General feedback</option>{data.visits.filter((visit) => visit.status === "VISITED").map((visit) => <option key={visit.id} value={visit.id}>{visit.visitCode}</option>)}</select></label><Select label="Rating" name="rating" options={[["5","5 - Excellent"],["4","4 - Good"],["3","3 - Average"],["2","2 - Poor"],["1","1 - Very poor"]]}/><Field label="Comments" name="comments"/><ActionButton saving={saving}>Save feedback</ActionButton></form></ActionBox> : null}
        <ActionBox icon={<CheckCircle2 size={17}/>} title="Record booking"><form className="grid gap-3" onSubmit={(event) => simple(event, "booking", "Booking recorded. Open the allotment link from Bookings below.")}><ProjectSelect projects={data.projects}/><label><span className="label">Available plot</span><select className="select h-10 w-full" name="plotId"><option value="">Select later</option>{data.plots.map((plot) => <option key={plot.id} value={plot.id}>{projectMap[plot.projectId]?.name} · {plot.code}</option>)}</select></label><Field label="Booking / sale value (₹)" name="amountInr" type="number"/><Field label="Notes" name="notes"/><ActionButton saving={saving}>Confirm booking</ActionButton></form></ActionBox>
        <ActionBox icon={<TicketCheck size={17}/>} title="Customer service ticket"><form className="grid gap-3" onSubmit={(event) => simple(event, "ticket", "Ticket created.")}><Select label="Category" name="category" options={[["Document request","Document request"],["Payment issue","Payment issue"],["Transfer request","Transfer request"],["Site issue","Site issue"],["Maintenance","Maintenance"],["Other","Other"]]}/><Field label="Subject" name="subject" required/><Field label="Description" name="description"/><UserSelect label="Assigned to" name="assignedToId" users={data.users}/><ActionButton saving={saving}>Create ticket</ActionButton></form></ActionBox>
        <Summary title="Follow-ups" items={data.followUps.map((item) => ({ id: item.id, title: item.actionType, detail: `${formatCrmLabel(item.status)} · ${new Date(item.dueAt).toLocaleString("en-IN")}` }))}/>
        <Summary title="Visits" items={data.visits.map((item) => ({ id: item.id, title: item.visitCode, detail: `${formatCrmLabel(item.status)} · ${new Date(item.scheduledAt).toLocaleString("en-IN")}` }))}/>
        <section className="rounded-lg border border-slate-200 bg-white p-4"><h2 className="font-semibold">Bookings</h2><div className="mt-3 space-y-3">{data.bookings.map((item) => <div className="rounded-md bg-slate-50 p-3 text-sm" key={item.id}><div className="font-medium">{item.bookingCode}</div><div className="text-xs text-slate-500">{projectMap[item.projectId]?.name} · ₹{Number(item.amountInr || 0).toLocaleString("en-IN")}</div>{item.plotId ? <Link className="mt-2 inline-flex items-center gap-1 font-medium text-[#2D5986]" href={`/app/projects/${item.projectId}/ownership/new-allotment?plotId=${item.plotId}&crmLeadId=${lead.id}`}>Start allotment <ExternalLink size={13}/></Link> : null}</div>)}{!data.bookings.length ? <div className="text-sm text-slate-500">No bookings yet.</div> : null}</div></section>
      </aside>
    </div>
  </div>;
}

function ActionBox({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <details className="rounded-lg border border-slate-200 bg-white"><summary className="flex cursor-pointer list-none items-center gap-2 p-4 font-semibold">{icon}{title}</summary><div className="border-t border-slate-100 p-4">{children}</div></details>; }
function ActionButton({ saving, children }: { saving: boolean; children: React.ReactNode }) { return <button className="btn-primary h-10 px-4" disabled={saving}>{children}</button>; }
function Field({ label, name, type = "text", required, defaultValue, placeholder }: { label: string; name: string; type?: string; required?: boolean; defaultValue?: string; placeholder?: string }) { return <label><span className="label">{label}{required ? " *" : ""}</span><input className="input h-10 w-full" defaultValue={defaultValue} name={name} placeholder={placeholder} required={required} type={type}/></label>; }
function Select({ label, name, options }: { label: string; name: string; options: string[][] }) { return <label><span className="label">{label}</span><select className="select h-10 w-full" name={name} required><option value="">Select</option>{options.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label>; }
function UserSelect({ label, name, users, defaultValue }: { label: string; name: string; users: User[]; defaultValue?: string | null }) { return <label><span className="label">{label}</span><select className="select h-10 w-full" defaultValue={defaultValue ?? ""} name={name}><option value="">Unassigned</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select></label>; }
function ProjectSelect({ projects }: { projects: Project[] }) { return <label><span className="label">Project</span><select className="select h-10 w-full" name="projectId" required><option value="">Select project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="grid grid-cols-[105px_1fr] gap-2"><dt className="text-slate-500">{label}</dt><dd className="font-medium text-slate-800">{value}</dd></div>; }
function Summary({ title, items }: { title: string; items: Array<{ id: string; title: string; detail: string }> }) { return <section className="rounded-lg border border-slate-200 bg-white p-4"><h2 className="font-semibold">{title}</h2><div className="mt-3 space-y-2">{items.slice(0, 5).map((item) => <div className="rounded-md bg-slate-50 p-3 text-sm" key={item.id}><div className="font-medium">{item.title}</div><div className="text-xs text-slate-500">{item.detail}</div></div>)}{!items.length ? <div className="text-sm text-slate-500">None recorded.</div> : null}</div></section>; }
function value(form: FormData, name: string) { return String(form.get(name) ?? "").trim(); }
function digits(value: string) { const result = value.replace(/\D/g, ""); return result.length === 10 ? `91${result}` : result; }
function budget(min: string | number | null, max: string | number | null) { if (!min && !max) return "Not specified"; return `${min ? `₹${Number(min).toLocaleString("en-IN")}` : "Any"} – ${max ? `₹${Number(max).toLocaleString("en-IN")}` : "Open"}`; }
function fillTemplate(body: string, customerName: string, projectName?: string) { return body.replaceAll("{{customer_name}}", customerName).replaceAll("{{project_name}}", projectName || "our project"); }
